FROM ubuntu:18.04

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get -y update \
    && apt-get install -y --no-install-recommends \
    ca-certificates \
    unzip \
    wget \
    python3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV ZULU_VERSION="zulu11.37.17-ca-fx-jdk11.0.6-linux_x64"
ENV ZULU_CHECKSUM="410c2f29c7496d801968e1e7db9ef4639cecabcf34c2cffcbf96437258dcf23da76529450dc34bcfba19613cba90e6f078bebba05bc509401a7d8f23ff943ad0  zulu11.37.17-ca-fx-jdk11.0.6-linux_x64.tar.gz"

RUN wget -q "https://cdn.azul.com/zulu/bin/${ZULU_VERSION}.tar.gz" \
    && echo "${ZULU_CHECKSUM}" | sha512sum -c \
    && tar -xf "${ZULU_VERSION}.tar.gz" \
    && mkdir -p /usr/java/ \
    && mv "${ZULU_VERSION}" /usr/java/ \
    && rm "${ZULU_VERSION}.tar.gz"

ENV ANT_VERSION="1.9.9" \
    ANT_HOME="/opt/ant" \
    JAVA_HOME="/usr/java/${ZULU_VERSION}"
ENV ANT_CHECKSUM="4d9e0f372bd9401993a4aed3b3c754813192b8d3093e772c6eb70465a7ae3c6de9ccc13d399d6df9b784a87a6504e4c6526d27a47887e4d89911438133745e0e  apache-ant-${ANT_VERSION}-bin.tar.gz"

RUN wget -q https://archive.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz \
    && echo "${ANT_CHECKSUM}" | sha512sum -c \
    && tar -xzf apache-ant-${ANT_VERSION}-bin.tar.gz \
    && mv "apache-ant-${ANT_VERSION}" "${ANT_HOME}" \
    && rm -v apache-ant-${ANT_VERSION}-bin.tar.gz

ENV NETBEANS_VERSION="11.3" \
    NETBEANS_HOME="/usr/local/netbeans" \
    NETBEANS_HELP_GITHUB="https://github.com/constellation-app/third-party-dependencies/blob/master/NetBeans%20Help"
ENV NETBEANS_CHECKSUM="ae828836138b5a4156d58df24dd4053be58018cb6b5beb179cb0f4cd8b5db72d2a7356a434d01157aacb78d228732950cf4e3a0b6c725da8e053b6ccd91075d6  netbeans-${NETBEANS_VERSION}-bin.zip"

RUN wget -q "http://apache.mirror.amaze.com.au/netbeans/netbeans/${NETBEANS_VERSION}/netbeans-${NETBEANS_VERSION}-bin.zip" \
    && echo "${NETBEANS_CHECKSUM}" | sha512sum -c \
    && unzip -q "netbeans-${NETBEANS_VERSION}-bin.zip" \
    && wget -q "${NETBEANS_HELP_GITHUB}/org-netbeans-modules-javahelp.jar?raw=true" -O netbeans/platform/modules/org-netbeans-modules-javahelp.jar \
    && wget -q "${NETBEANS_HELP_GITHUB}/jhall-2.0_05.jar?raw=true" -O netbeans/platform/modules/ext/jhall-2.0_05.jar \
    && mv netbeans "${NETBEANS_HOME}" \
    && rm "netbeans-${NETBEANS_VERSION}-bin.zip"

ENV JACOCO_VERSION="0.8.5" \
    JACOCO_HOME="/opt/jacoco"
ENV JACOCO_CHECKSUM="2be070c33da2b9152ec9cd9f42f39190e6cbe9f245627cbd1a6750a07fb380be113b1e63da47738377d76d3f739f75d94b60b618a8c17a5c7581312ffdf2dfc3  jacoco-${JACOCO_VERSION}.zip"

RUN mkdir -p ${JACOCO_HOME}/ \
    && wget -q "http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/${JACOCO_VERSION}/jacoco-${JACOCO_VERSION}.zip" -O jacoco-${JACOCO_VERSION}.zip \
    && echo "${JACOCO_CHECKSUM}" | sha512sum -c \
    && mv "jacoco-${JACOCO_VERSION}.zip" "${JACOCO_HOME}/" \
    && unzip -q "${JACOCO_HOME}/jacoco-${JACOCO_VERSION}.zip" -d "${JACOCO_HOME}/" \
    && rm "${JACOCO_HOME}/jacoco-${JACOCO_VERSION}.zip"

ENV JACOCO_AGENT="${JACOCO_HOME}/lib/jacocoagent.jar" \
    PATH="${PATH}:${ANT_HOME}/bin:${JAVA_HOME}/bin"
