FROM ubuntu:18.04

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get -y update \
    && apt-get install -y --no-install-recommends \
    ca-certificates \
    unzip \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV ZULU_VERSION="zulu8.38.0.13-ca-fx-jdk8.0.212-linux_x64"
ENV ZULU_CHECKSUM="3f885e6e476097ecc6ef2b2c563b4bb76ffea107b11994e671ae63d6eb62ba4e0ce64022e36fa37f02906f68068849958a40bc4889771899b630013de678dd85  ${ZULU_VERSION}.tar.gz"

RUN wget -q "https://cdn.azul.com/zulu/bin/${ZULU_VERSION}.tar.gz" \
    && echo "${ZULU_CHECKSUM}" | sha512sum -c \
    && tar -xf "${ZULU_VERSION}.tar.gz" \
    && mkdir -p /usr/java/ \
    && mv "${ZULU_VERSION}" /usr/java/ \
    && rm "${ZULU_VERSION}.tar.gz"

ENV ANT_VERSION="1.9.9" \
    ANT_HOME="/opt/ant" \
    JAVA_HOME="/usr/java/${ZULU_VERSION}"
ENV ANT_CHECKSUM="4d9e0f372bd9401993a4aed3b3c754813192b8d3093e772c6eb70465a7ae3c6de9ccc13d399d6df9b784a87a6504e4c6526d27a47887e4d89911438133745e0e  apache-ant-${ANT_VERSION}-bin.tar.gz"

RUN wget -q https://archive.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz \
    && echo "${ANT_CHECKSUM}" | sha512sum -c \
    && tar -xzf apache-ant-${ANT_VERSION}-bin.tar.gz \
    && mv "apache-ant-${ANT_VERSION}" "${ANT_HOME}" \
    && rm -v apache-ant-${ANT_VERSION}-bin.tar.gz

ENV NETBEANS_VERSION="8.2" \
    NETBEANS_BUNDLE="javaee-linux.sh"
ENV NETBEANS_CHECKSUM="61c69707c2261a030098ac059b92212df5f14f397447b4221655b8158f2db603d12bb836d78c7d7749dc0d7e67f3b5d504371b58f5612201491c872283b7919d  netbeans-${NETBEANS_VERSION}-${NETBEANS_BUNDLE}"

RUN wget -q http://download.netbeans.org/netbeans/${NETBEANS_VERSION}/final/bundles/netbeans-${NETBEANS_VERSION}-${NETBEANS_BUNDLE} \
    && echo "${NETBEANS_CHECKSUM}" | sha512sum -c \
    && chmod +x "netbeans-${NETBEANS_VERSION}-${NETBEANS_BUNDLE}" \
    && ./netbeans-${NETBEANS_VERSION}-${NETBEANS_BUNDLE} --silent \
    && rm netbeans-${NETBEANS_VERSION}-${NETBEANS_BUNDLE}

ENV JACOCO_VERSION="0.8.1" \
    JACOCO_HOME="/opt/jacoco"
ENV JACOCO_CHECKSUM="f6d67930c701c87f47ec1ee53e3b4ff932909063c3efcbcf3ff207990d5c6a9fbf3eec90276d01bc02b5eebce732eb9525f651684189c0813f7a75ffa9d744aa  jacoco-${JACOCO_VERSION}.zip"

RUN mkdir -p ${JACOCO_HOME}/ \
    && wget -q "http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/${JACOCO_VERSION}/jacoco-${JACOCO_VERSION}.zip" -O jacoco-${JACOCO_VERSION}.zip \
    && echo "${JACOCO_CHECKSUM}" | sha512sum -c \
    && mv "jacoco-${JACOCO_VERSION}.zip" "${JACOCO_HOME}/" \
    && unzip -q "${JACOCO_HOME}/jacoco-${JACOCO_VERSION}.zip" -d "${JACOCO_HOME}/" \
    && rm "${JACOCO_HOME}/jacoco-${JACOCO_VERSION}.zip"

ENV NETBEANS_HOME="/usr/local/netbeans-${NETBEANS_VERSION}" \
    JACOCO_AGENT="${JACOCO_HOME}/lib/jacocoagent.jar" \
    PATH="${PATH}:${ANT_HOME}/bin:${JAVA_HOME}/bin"
