/*
 * Copyright 2010-2021 Australian Signals Directorate
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package au.gov.asd.tac.constellation.views.find.gui;

import java.awt.Color;

/**
 * GUI Class that is used to handle input of float based queries in conjunction
 * with the <code>FindTopComponent</code> / <code>FindCriteriaPanel</code>
 * classes.
 *
 * @author betelgeuse
 * @see FindTopComponent
 * @see FindCriteriaPanel
 */
public class FloatCriteriaPanel extends javax.swing.JPanel {

    private final FindCriteriaPanel parentPanel;
    private float validFloat1 = 0.0F;
    private float validFloat2 = 0.0F;

    /**
     * Creates a new form <code>FloatCriteriaPanel</code> with no prefilled
     * content.
     *
     * @param parent The <code>FindCriteriaPanel</code> that owns this panel.
     */
    public FloatCriteriaPanel(final FindCriteriaPanel parent) {
        initComponents();

        this.parentPanel = parent;
    }

    /**
     * Constructs a new <code>FloatCriteriaPanel</code> with prefilled content.
     *
     * @param parent The <code>FindCriteriaPanel</code> that owns this panel.
     * @param floatA The value to place in the form's first input box.
     * @param floatB The value to place in the form's second input box.
     * @param isBetween Whether or not the second input box should be shown.
     */
    public FloatCriteriaPanel(final FindCriteriaPanel parent, final float floatA,
            final float floatB, final boolean isBetween) {
        this(parent);

        txtFloat1.setText(Float.toString(floatA));
        txtFloat2.setText(Float.toString(floatB));

        setUIState(isBetween);

        this.validate();
        this.repaint();
    }

    /**
     * Returns the current state of this panel's first input box.
     *
     * @return The parsed value of the first input box.
     */
    public float getFirstFloat() {
        if (validateFloat(txtFloat1.getText())) {
            return Float.parseFloat(txtFloat1.getText());
        } else {
            return validFloat1;
        }
    }

    /**
     * Returns the current state of this panel's second input box.
     *
     * @return The parsed value of the second input box.
     */
    public float getSecondFloat() {
        if (validateFloat(txtFloat2.getText())) {
            return Float.parseFloat(txtFloat2.getText());
        } else {
            return validFloat2;
        }
    }

    /**
     * Method that adjusts the form to handle multiple float input.
     *
     * @param isBetween <code>true</code> if form should show the extended input
     * controls, <code>false</code> if it should not.
     */
    public void setUIState(final boolean isBetween) {
        lblAnd.setVisible(isBetween);
        txtFloat2.setVisible(isBetween);
        lblFloat2.setVisible(isBetween);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFloat1 = new javax.swing.JFormattedTextField();
        lblFloat1 = new javax.swing.JLabel();
        txtFloat2 = new javax.swing.JFormattedTextField();
        lblFloat2 = new javax.swing.JLabel();
        lblAnd = new javax.swing.JLabel();

        setOpaque(false);

        txtFloat1.setText(org.openide.util.NbBundle.getMessage(FloatCriteriaPanel.class, "FloatCriteriaPanel.txtFloat1.text")); // NOI18N
        txtFloat1.setName("txtFloat1"); // NOI18N
        txtFloat1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFloat1FocusLost(evt);
            }
        });
        txtFloat1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFloat1KeyReleased(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblFloat1, org.openide.util.NbBundle.getMessage(FloatCriteriaPanel.class, "FloatCriteriaPanel.lblFloat1.text")); // NOI18N
        lblFloat1.setMaximumSize(new java.awt.Dimension(0, 100));

        txtFloat2.setText(org.openide.util.NbBundle.getMessage(FloatCriteriaPanel.class, "FloatCriteriaPanel.txtFloat2.text")); // NOI18N
        txtFloat2.setName("txtFloat2"); // NOI18N
        txtFloat2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFloat2FocusLost(evt);
            }
        });
        txtFloat2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFloat2KeyReleased(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblFloat2, org.openide.util.NbBundle.getMessage(FloatCriteriaPanel.class, "FloatCriteriaPanel.lblFloat2.text")); // NOI18N
        lblFloat2.setMaximumSize(new java.awt.Dimension(0, 100));

        org.openide.awt.Mnemonics.setLocalizedText(lblAnd, org.openide.util.NbBundle.getMessage(FloatCriteriaPanel.class, "FloatCriteriaPanel.lblAnd.text")); // NOI18N
        lblAnd.setMaximumSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFloat1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFloat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFloat2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFloat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAnd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFloat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFloat2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFloat1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFloat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event handler for <code>txtFloat2</code> key releases.
     * <p>
     * This triggers float validation checks.
     *
     * @param evt The registered event.
     */
    private void txtFloat2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFloat2KeyReleased

        if (!validateFloat(txtFloat2.getText())) {
            txtFloat2.setForeground(Color.RED);
        } else {
            txtFloat2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtFloat2KeyReleased

    /**
     * Event handler for <code>txtFloat1</code> key releases.
     * <p>
     * This triggers float validation checks.
     *
     * @param evt The registered event.
     */
    private void txtFloat1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFloat1KeyReleased

        if (!validateFloat(txtFloat1.getText())) {
            txtFloat1.setForeground(Color.RED);
        } else {
            txtFloat1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtFloat1KeyReleased

    /**
     * Event handler for <code>txtFloat1</code> loss of focus.
     * <p>
     * This triggers float validation checks.
     *
     * @param evt The registered event.
     */
    private void txtFloat1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFloat1FocusLost

        if (validateFloat(txtFloat1.getText())) {
            validFloat1 = Float.parseFloat(txtFloat1.getText());
        } else {
            txtFloat1.setText(Float.toString(validFloat1));
            txtFloat1.setForeground(Color.BLACK);
        }

        // Something may have changed, so save the state:
        parentPanel.saveStateToGraph();
    }//GEN-LAST:event_txtFloat1FocusLost

    /**
     * Event handler for <code>txtFloat2</code> loss of focus.
     * <p>
     * This triggers float validation checks.
     *
     * @param evt The registered event.
     */
    private void txtFloat2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFloat2FocusLost

        if (validateFloat(txtFloat2.getText())) {
            validFloat2 = Float.parseFloat(txtFloat2.getText());
        } else {
            txtFloat2.setText(Float.toString(validFloat2));
            txtFloat2.setForeground(Color.BLACK);
        }

        // Something may have changed, so save the state:
        parentPanel.saveStateToGraph();
    }//GEN-LAST:event_txtFloat2FocusLost
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAnd;
    private javax.swing.JLabel lblFloat1;
    private javax.swing.JLabel lblFloat2;
    private javax.swing.JFormattedTextField txtFloat1;
    private javax.swing.JFormattedTextField txtFloat2;
    // End of variables declaration//GEN-END:variables

    /**
     * Helper method that determines whether a given string can be parsed into a
     * float.
     *
     * @param potential String to test.
     * @return <code>true</code> if given string is able to be * parsed,
     * <code>false</code> if it is not.
     */
    private boolean validateFloat(final String potential) {
        try {
            Float.parseFloat(potential);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }
}
