/*
 * Copyright 2010-2019 Australian Signals Directorate
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package au.gov.asd.tac.constellation.preferences;

/**
 * UI panel to define the session parameters
 *
 * @author aldebaran30701
 */
final class GraphOptionsPanel extends javax.swing.JPanel {

    private final GraphOptionsPanelController controller;

    public GraphOptionsPanel(final GraphOptionsPanelController controller) {
        this.controller = controller;
        initComponents();

        /**
         * REMOVE this section when implementing custom blaze colours Introduced
         * with fix for issue #158 FROM HERE
         */
        BlazeColourPanel.setVisible(false);
        BlazeColourPlaceholder.setVisible(false);
        BlazeColourDescription.setVisible(false);
        /**
         * TO HERE
         */
    }

    public void setBlazeSize(final int value) {
        blazeSlider.setValue(value);
    }

    public void setBlazeOpacity(final int value) {
        blazeOpacitySlider.setValue(value);
    }

    public int getBlazeSize() {
        return blazeSlider.getValue();
    }

    public int getBlazeOpacity() {
        return blazeOpacitySlider.getValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blazeSizePanel = new javax.swing.JPanel();
        blazeSlider = new javax.swing.JSlider();
        BlazeSizeDescription = new javax.swing.JLabel();
        blazeOpacitySlider = new javax.swing.JSlider();
        BlazeSizeDescription1 = new javax.swing.JLabel();
        BlazeColourPanel = new javax.swing.JPanel();
        BlazeColourDescription = new javax.swing.JLabel();
        BlazeColourPlaceholder = new javax.swing.JLabel();
        notePanel = new javax.swing.JPanel();
        noteLabel = new javax.swing.JLabel();

        blazeSizePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(GraphOptionsPanel.class, "GraphOptionsPanel.blazeSizePanel.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(BlazeSizeDescription, org.openide.util.NbBundle.getMessage(GraphOptionsPanel.class, "GraphOptionsPanel.BlazeSizeDescription.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(BlazeSizeDescription1, org.openide.util.NbBundle.getMessage(GraphOptionsPanel.class, "GraphOptionsPanel.BlazeSizeDescription1.text")); // NOI18N

        javax.swing.GroupLayout blazeSizePanelLayout = new javax.swing.GroupLayout(blazeSizePanel);
        blazeSizePanel.setLayout(blazeSizePanelLayout);
        blazeSizePanelLayout.setHorizontalGroup(
            blazeSizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blazeSizePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(blazeSizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BlazeSizeDescription1)
                    .addComponent(BlazeSizeDescription, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(blazeSizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(blazeOpacitySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blazeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        blazeSizePanelLayout.setVerticalGroup(
            blazeSizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blazeSizePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(blazeSizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BlazeSizeDescription)
                    .addComponent(blazeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(blazeSizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blazeOpacitySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BlazeSizeDescription1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BlazeColourPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(GraphOptionsPanel.class, "GraphOptionsPanel.blazeColourPanel.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(BlazeColourDescription, org.openide.util.NbBundle.getMessage(GraphOptionsPanel.class, "GraphOptionsPanel.BlazeColourDescription.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(BlazeColourPlaceholder, org.openide.util.NbBundle.getMessage(GraphOptionsPanel.class, "GraphOptionsPanel.BlazeColourPlaceholder.text")); // NOI18N

        javax.swing.GroupLayout BlazeColourPanelLayout = new javax.swing.GroupLayout(BlazeColourPanel);
        BlazeColourPanel.setLayout(BlazeColourPanelLayout);
        BlazeColourPanelLayout.setHorizontalGroup(
            BlazeColourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlazeColourPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BlazeColourDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(BlazeColourPlaceholder)
                .addGap(94, 94, 94))
        );
        BlazeColourPanelLayout.setVerticalGroup(
            BlazeColourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlazeColourPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BlazeColourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BlazeColourDescription)
                    .addComponent(BlazeColourPlaceholder))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        notePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(GraphOptionsPanel.class, "GraphOptionsPanel.notePanel.border.title"))); // NOI18N

        noteLabel.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(noteLabel, org.openide.util.NbBundle.getMessage(GraphOptionsPanel.class, "GraphOptionsPanel.noteLabel.text")); // NOI18N

        javax.swing.GroupLayout notePanelLayout = new javax.swing.GroupLayout(notePanel);
        notePanel.setLayout(notePanelLayout);
        notePanelLayout.setHorizontalGroup(
            notePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(noteLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        notePanelLayout.setVerticalGroup(
            notePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noteLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blazeSizePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BlazeColourPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(notePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(blazeSizePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BlazeColourPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        blazeSizePanel.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(GraphOptionsPanel.class, "GraphOptionsPanel.blazeSizePanel.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BlazeColourDescription;
    private javax.swing.JPanel BlazeColourPanel;
    private javax.swing.JLabel BlazeColourPlaceholder;
    private javax.swing.JLabel BlazeSizeDescription;
    private javax.swing.JLabel BlazeSizeDescription1;
    private javax.swing.JSlider blazeOpacitySlider;
    private javax.swing.JPanel blazeSizePanel;
    private javax.swing.JSlider blazeSlider;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JPanel notePanel;
    // End of variables declaration//GEN-END:variables
}
