/*
 * Copyright 2010-2025 Australian Signals Directorate
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package au.gov.asd.tac.constellation.preferences;

import java.util.Collections;
import java.util.Map;
import java.util.TreeMap;
import java.util.prefs.Preferences;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.openide.util.NbPreferences;

/**
 * UI panel for View options.
 *
 * @author sol695510
 */
public class ViewOptionsPanel extends JPanel {

    private final DefaultTableModel tableModel;
    private final Preferences prefs = NbPreferences.forModule(ViewPreferenceKeys.class);
    private final Map<String, Boolean> defaultOptions = ViewPreferenceKeys.getDefaultViewOptions();

    protected ViewOptionsPanel() {
        tableModel = new DefaultTableModel(new Object[]{"View", "Floating"}, 0) {
            @Override
            public Class getColumnClass(final int column) {
                return switch (column) {
                    case 0 ->
                        String.class; // View names.
                    default ->
                        Boolean.class; // Checkboxes.
                };
            }

            @Override
            public boolean isCellEditable(final int row, final int column) {
                return switch (column) {
                    case 0 ->
                        false;
                    default ->
                        true;
                };
            }
        };

        final Map<String, Boolean> options = getOptionsFromPrefs().isEmpty() ? defaultOptions : getOptionsFromPrefs();

        for (final Map.Entry<String, Boolean> entry : options.entrySet()) {
            tableModel.addRow(new Object[]{entry.getKey(), entry.getValue()});
        }

        initComponents();
        jTable.setModel(tableModel);
        jTable.getTableHeader().setReorderingAllowed(false);
    }

    protected final void fireTableDataChanged() {
        tableModel.fireTableDataChanged();
    }

    protected final Map<String, Boolean> getOptionsFromUI() {
        final Map<String, Boolean> optionsFromUI = new TreeMap<>();

        for (int i = 0; i < tableModel.getRowCount(); i++) {
            optionsFromUI.put((String) tableModel.getValueAt(i, 0), (Boolean) tableModel.getValueAt(i, 1));
        }

        return Collections.unmodifiableMap(optionsFromUI);
    }

    protected final Map<String, Boolean> getOptionsFromPrefs() {
        final Map<String, Boolean> optionsFromPrefs = new TreeMap<>();

        for (final Map.Entry<String, Boolean> entry : defaultOptions.entrySet()) {
            optionsFromPrefs.put(entry.getKey(), prefs.getBoolean(entry.getKey(), entry.getValue()));
        }

        return Collections.unmodifiableMap(optionsFromPrefs);
    }

    private final JTable getJTable() {
        return jTable;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(new java.awt.BorderLayout());

        jScrollPane.setViewportView(jTable);

        add(jScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
