/*
 * Copyright 2010-2021 Australian Signals Directorate
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package au.gov.asd.tac.constellation.utilities.gui.filechooser;

import java.io.File;
import org.openide.filesystems.FileChooserBuilder;

/**
 * {@link Runnable} that opens file chooser dialog generated by the builder and
 * waits for the user to either select a file or cancel.
 * 
 * @author formalhaunt
 */
public class ShowFileChooserDialog implements Runnable {
    private final FileChooserBuilder fileChooserBuilder;
    private final FileChooserMode fileChooserMode;
        
    private File selectedFile = null;

    /**
     * Creates a new show dialog task.
     *
     * @param fileChooserBuilder the file chooser builder that will provide the
     *     file chooser to open
     * @param fileChooserMode the mode to open the file chooser in
     */
    public ShowFileChooserDialog(final FileChooserBuilder fileChooserBuilder,
                                 final FileChooserMode fileChooserMode) {
        this.fileChooserBuilder = fileChooserBuilder;
        this.fileChooserMode = fileChooserMode;
    }

    /**
     * Opens the file chooser dialog in the correct mode and waits for a user
     * response.
     */
    @Override
    public void run() {
        if (fileChooserMode == FileChooserMode.OPEN) {
            selectedFile = fileChooserBuilder.showOpenDialog();
        } else if (fileChooserMode == FileChooserMode.SAVE) {
            selectedFile = fileChooserBuilder.showSaveDialog();
        }
    }

    /**
     * Gets the selected file.
     *
     * @return the selected file or null if the user selected cancel
     */
    public File getSelectedFile() {
        return selectedFile;
    }
}
