package au.gov.asd.tac.constellation.visual.opengl.utilities;

import au.gov.asd.tac.constellation.visual.opengl.utilities.glyphs.ConstellationLabelFonts;
import au.gov.asd.tac.constellation.visual.opengl.utilities.glyphs.FontInfo;
import au.gov.asd.tac.constellation.visual.opengl.utilities.glyphs.GlyphManagerBI;
import java.awt.Color;
import java.awt.Component;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JScrollPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 * An options panel allowing customisation of label fonts.
 * 
 * @author algol
 * @author cygnus_x-1
 */
final class LabelFontsOptionsPanel extends javax.swing.JPanel {

    private final LabelFontsOptionsPanelController controller;

    LabelFontsOptionsPanel(LabelFontsOptionsPanelController controller) {
        this.controller = controller;
        initComponents();

        final NumberedTextArea numberedTextArea = new NumberedTextArea(fontListTextArea);
        fontListScrollPane.setRowHeaderView(numberedTextArea);

        final String[] scripts = Arrays.stream(Character.UnicodeScript.class.getEnumConstants())
                .map(s -> s.toString())
                .sorted()
                .toArray(String[]::new);
        Arrays.sort(scripts);
        addScriptComboBox.setModel(new DefaultComboBoxModel<>(scripts));

        fontListTextArea.getDocument().addDocumentListener(new DocumentListener() {
            
            @Override
            public void insertUpdate(final DocumentEvent e) {
                numberedTextArea.updateLineNumbers();
            }

            @Override
            public void removeUpdate(final DocumentEvent e) {
                numberedTextArea.updateLineNumbers();
            }

            @Override
            public void changedUpdate(final DocumentEvent e) {
                numberedTextArea.updateLineNumbers();
            }
        });
        fontListTextArea.setCaretPosition(0);
    }
    
    private void setLabelFontsPanelEnabled(final boolean useDefaultSettings) {
        for (final Component c : labelFontsPanel.getComponents()) {
            if (c instanceof JScrollPane) {
                ((JScrollPane) c).getViewport().getView().setEnabled(useDefaultSettings);
            } else {
                c.setEnabled(useDefaultSettings);
            }
        }
    }

    boolean getUseDefaultSettings() {
        return useDefaultCheckBox.isSelected();
    }
    
    void setUseDefaultSettings(final boolean useDefaultSettings) {
        useDefaultCheckBox.setSelected(useDefaultSettings);
        if (useDefaultSettings) {
            final ConstellationLabelFonts defaultFonts = ConstellationLabelFonts.getDefault();
            setUseMultiFonts(defaultFonts.getUseMultiFonts());
            setFontList(defaultFonts.getFontListString());
        }
        setLabelFontsPanelEnabled(!useDefaultSettings);
    }
    
    public boolean getUseMultiFonts() {
        return useMultiFontCheckBox.isSelected();
    }

    public void setUseMultiFonts(final boolean useMultiFonts) {
        useMultiFontCheckBox.setSelected(useMultiFonts);
    }
    
    public String getFontList() {
        return fontListTextArea.getText().trim();
    }

    public void setFontList(final String fontList) {
        fontListTextArea.setText(fontList);
    }
    
    public void setAvailableFonts(final String[] availableFonts) {
        addFontComboBox.setModel(new DefaultComboBoxModel<>(availableFonts));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        useDefaultCheckBox = new javax.swing.JCheckBox();
        labelFontsPanel = new javax.swing.JPanel();
        fontListScrollPane = new javax.swing.JScrollPane();
        fontListTextArea = new javax.swing.JTextArea();
        descriptionScrollPane = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        addFontLabel = new javax.swing.JLabel();
        addFontComboBox = new javax.swing.JComboBox<>();
        addFontButton = new javax.swing.JButton();
        addScriptLabel = new javax.swing.JLabel();
        addScriptComboBox = new javax.swing.JComboBox<>();
        addScriptButton = new javax.swing.JButton();
        validateButton = new javax.swing.JButton();
        useMultiFontCheckBox = new javax.swing.JCheckBox();
        validateLabel = new javax.swing.JLabel();

        useDefaultCheckBox.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(useDefaultCheckBox, org.openide.util.NbBundle.getMessage(LabelFontsOptionsPanel.class, "LabelFontsOptionsPanel.useDefaultCheckBox.text")); // NOI18N
        useDefaultCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useDefaultCheckBoxActionPerformed(evt);
            }
        });

        labelFontsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(LabelFontsOptionsPanel.class, "LabelFontsOptionsPanel.labelFontsPanel.border.title"))); // NOI18N

        fontListTextArea.setColumns(20);
        fontListTextArea.setRows(5);
        fontListTextArea.setText(org.openide.util.NbBundle.getMessage(LabelFontsOptionsPanel.class, "LabelFontsOptionsPanel.fontListTextArea.text")); // NOI18N
        fontListScrollPane.setViewportView(fontListTextArea);

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setBackground(java.awt.SystemColor.control);
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        descriptionTextArea.setLineWrap(true);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setText(org.openide.util.NbBundle.getMessage(LabelFontsOptionsPanel.class, "LabelFontsOptionsPanel.descriptionTextArea.text")); // NOI18N
        descriptionTextArea.setWrapStyleWord(true);
        descriptionTextArea.setBorder(null);
        descriptionTextArea.setFocusable(false);
        descriptionScrollPane.setViewportView(descriptionTextArea);

        addFontLabel.setLabelFor(addFontButton);
        org.openide.awt.Mnemonics.setLocalizedText(addFontLabel, org.openide.util.NbBundle.getMessage(LabelFontsOptionsPanel.class, "LabelFontsOptionsPanel.addFontLabel.text")); // NOI18N

        addFontComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.openide.awt.Mnemonics.setLocalizedText(addFontButton, org.openide.util.NbBundle.getMessage(LabelFontsOptionsPanel.class, "LabelFontsOptionsPanel.addFontButton.text")); // NOI18N
        addFontButton.setActionCommand(org.openide.util.NbBundle.getMessage(LabelFontsOptionsPanel.class, "LabelFontsOptionsPanel.addFontButton.actionCommand")); // NOI18N
        addFontButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFontButtonActionPerformed(evt);
            }
        });

        addScriptLabel.setLabelFor(addScriptButton);
        org.openide.awt.Mnemonics.setLocalizedText(addScriptLabel, org.openide.util.NbBundle.getMessage(LabelFontsOptionsPanel.class, "LabelFontsOptionsPanel.addScriptLabel.text")); // NOI18N

        addScriptComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.openide.awt.Mnemonics.setLocalizedText(addScriptButton, org.openide.util.NbBundle.getMessage(LabelFontsOptionsPanel.class, "LabelFontsOptionsPanel.addScriptButton.text")); // NOI18N
        addScriptButton.setActionCommand(org.openide.util.NbBundle.getMessage(LabelFontsOptionsPanel.class, "LabelFontsOptionsPanel.addScriptButton.actionCommand")); // NOI18N
        addScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addScriptButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(validateButton, org.openide.util.NbBundle.getMessage(LabelFontsOptionsPanel.class, "LabelFontsOptionsPanel.validateButton.text")); // NOI18N
        validateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(useMultiFontCheckBox, org.openide.util.NbBundle.getMessage(LabelFontsOptionsPanel.class, "LabelFontsOptionsPanel.useMultiFontCheckBox.text")); // NOI18N

        validateLabel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        validateLabel.setForeground(new java.awt.Color(153, 153, 153));
        validateLabel.setLabelFor(validateButton);
        org.openide.awt.Mnemonics.setLocalizedText(validateLabel, org.openide.util.NbBundle.getMessage(LabelFontsOptionsPanel.class, "LabelFontsOptionsPanel.validateLabel.text")); // NOI18N

        javax.swing.GroupLayout labelFontsPanelLayout = new javax.swing.GroupLayout(labelFontsPanel);
        labelFontsPanel.setLayout(labelFontsPanelLayout);
        labelFontsPanelLayout.setHorizontalGroup(
            labelFontsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, labelFontsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(labelFontsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(labelFontsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(labelFontsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(labelFontsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fontListScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(labelFontsPanelLayout.createSequentialGroup()
                                    .addComponent(useMultiFontCheckBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(validateButton))
                                .addComponent(validateLabel)
                                .addGroup(labelFontsPanelLayout.createSequentialGroup()
                                    .addComponent(addFontLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addFontComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(addFontButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, labelFontsPanelLayout.createSequentialGroup()
                            .addComponent(addScriptLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addScriptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(addScriptButton))
                .addGap(18, 18, 18)
                .addComponent(descriptionScrollPane)
                .addContainerGap())
        );
        labelFontsPanelLayout.setVerticalGroup(
            labelFontsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelFontsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(labelFontsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionScrollPane)
                    .addGroup(labelFontsPanelLayout.createSequentialGroup()
                        .addComponent(fontListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(labelFontsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(validateButton)
                            .addComponent(useMultiFontCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(labelFontsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addFontComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addFontLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addFontButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(labelFontsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addScriptComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addScriptLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addScriptButton))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFontsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(useDefaultCheckBox)
                        .addGap(0, 537, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(useDefaultCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFontsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addFontButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFontButtonActionPerformed
        // Add the selected font name to the end of the text area.
        final String fontName = (String) addFontComboBox.getSelectedItem();
        fontListTextArea.insert(fontName + "\n", fontListTextArea.getCaretPosition());
    }//GEN-LAST:event_addFontButtonActionPerformed

    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateButtonActionPerformed
        final String text = fontListTextArea.getText();
        final FontInfo.ParsedFontInfo pfi = FontInfo.parseFontInfo(text.split("\n"), GlyphManagerBI.DEFAULT_FONT_SIZE);
        if (pfi.messages.isEmpty()) {
            validateLabel.setText("OK");
            validateLabel.setForeground(Color.GREEN.darker());
        } else {
            validateLabel.setText(pfi.messages.get(0));
            validateLabel.setForeground(Color.RED.darker());
        }
    }//GEN-LAST:event_validateButtonActionPerformed

    private void addScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addScriptButtonActionPerformed
        final String scriptName = (String) addScriptComboBox.getSelectedItem();
        fontListTextArea.insert("," + scriptName, fontListTextArea.getCaretPosition());
    }//GEN-LAST:event_addScriptButtonActionPerformed

    private void useDefaultCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useDefaultCheckBoxActionPerformed
        setUseDefaultSettings(useDefaultCheckBox.isSelected());
    }//GEN-LAST:event_useDefaultCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFontButton;
    private javax.swing.JComboBox<String> addFontComboBox;
    private javax.swing.JLabel addFontLabel;
    private javax.swing.JButton addScriptButton;
    private javax.swing.JComboBox<String> addScriptComboBox;
    private javax.swing.JLabel addScriptLabel;
    private javax.swing.JScrollPane descriptionScrollPane;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JScrollPane fontListScrollPane;
    private javax.swing.JTextArea fontListTextArea;
    private javax.swing.JPanel labelFontsPanel;
    private javax.swing.JCheckBox useDefaultCheckBox;
    private javax.swing.JCheckBox useMultiFontCheckBox;
    private javax.swing.JButton validateButton;
    private javax.swing.JLabel validateLabel;
    // End of variables declaration//GEN-END:variables
}
