name: Trigger GHPages to update documentation
# When documentation needs an update, a push to documentation_update branch will trigger
# this action to send a request to the GHPages repository to update the online documentation.

on:
  push:
    branches:
      - documentation_update

jobs:
  trigger-doco-update:
    runs-on: ubuntu-latest
    steps:
      - name: set tag env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: test env set correctly # found here: https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: trigger repository event
        if: github.event.action != 'pong'
        run: |
          curl -X POST https://api.github.com/repos/constellation-app/constellation-app.github.io/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
